### ISSUE TITLE
User Auth Issues

### ISSUE THREAD

**Issue by bencbernstein** [Classical-SB/invisible-college-admin#103]
When logging in, I often get "fail to fetch" and sometimes "NetworkError when attempting to fetch resource."

While adding properties to choice sets, I sometimes get a long spinning wheel and then get logged out.

I'm not sure, but this might be remedied by only hitting login ONCE and then waiting for a long time.

**Comment by bencbernstein** [comment]
i haven't been having problems... did you fix this?

**Comment by OLI9292** [comment]
ya short term fix until merge is done
