### ISSUE TITLE
Enhanced sequencing 

### ISSUE THREAD

**Issue by OLI9292** [Classical-SB/invisible-college-admin#112]
no guessing on questions

**Comment by OLI9292** [comment]
- [ ] description
- [ ] choose between choice sets
- [ ] choose between k/v
- [ ] choose between images
- [ ] question suggester

**Comment by bencbernstein** [comment]
Seeing all the possible questions for a data point is great, elucidating.

Choosing between images and also seeing, in small text, the answer would be nice too.

The next step may be the question suggester -> that suggests minimal pair chains (aka daisy chain) question off your seed.

We could start by trying shortest levenshtein distance of the prompt or answer with another key, value or the concept itself in the curriculum, picking the one with the lowest obscurity first. A guess is that the answer is generally the most preferable to chain off, which could be the value or concept (and down the road, the key, which is a question type we haven't implemented yet)

Quick Example (these are kind of obscure concepts. imagine they all have pictures on them):

Seed Question: Halia lives? Answer: Island of Rhodes

Algorithm Suggests:
(daisy chain length between 2 and 6 ... algo picked 2):
Prompt: Lives in the Island of Rhodes? Answer: Hegetoria
Prompt: Hegetoria's husband? Answer: Ochimus

Algorithm Suggests:
(back to chaining off seed)
(algo picked length 3):
Prompt: Halia's parents? Answer: Thalassa
Prompt: Thalassa is god of? Answer: The sea
Prompt: Lives in the Aegean Sea? Answer: Poseidon

**Comment by bencbernstein** [comment]
After several days of testing manual sequencing, here's what I suggest doing for question suggester V1:

For each question you input, show suggestions before and after based on
	 1) whether it's a read mode or a question and 
	 2) Levenshtein distance of the concept and value.

Each question type should have an assignable obscurity. Determine question type by obscurity. Example:
	Word to Image: 1
	Word to Definition: 2
	Word to Tag [User Input]

### UX Part 1 ###

User inputs: Abraxas Read Mode:
	Abraxas (concept) is (key) the embodied form of God according to Gnostic Christians (value)

=== Suggestions BEFORE ===
	Gnosticism Read Mode
		Gnosticism is a group of ancient religious ideas
	Gnosis Definition Read Mode
		Gnosis means means knowledge, or the spiritual knowledge to liberate the divine in each 		human
		
=== Algo:
	Because it's read mode algo knows user needs these concepts BEFORE to atomically understand the VALUE.
	Suggest easiest obscurity data based on concepts in read mode (found: Gnostic, Gnosticism, user hasn't seen these words before so display the lowest obscurity property)

=== Suggestions AFTER ===
	Abraxas Word to Tag Question
		Head? Rooster (Symbolizing Wakefulness)
	Abraxas Word to Tag Question
		Body? Human (Symbolizing Logic)
	Abraxas Sylvata Word to Image
	Abraxas Stone Word to Image

=== Algo:
	Because user has viewed in read mode Abraxas obscurity 1 data (Abraxas is), suggest next easiest obscurity question for Abraxas (tags). Also suggest similar concepts to ABRAXAS starting with their lowest obscurity. 

### UX Part 2 ###
	For each question user approved in suggester, the user can hit a suggest button to have the suggester re-run on that question. 
	Let's say user approves "gnosis" definition read mode before the ABRAXAS READ MODE and selects it. 

I would then get recommended the word "agnostic", as a question afterward since it's close to gnosis.
	Agnostic Definition to Word:
		The view that the existence of God is NOT (a) KNOWABLE (GNOSTIC)
	answer: agnostic

**Comment by bencbernstein** [comment]
i think we may have figured out this implementation which would be:

user enters "hardcoded" questions for that sequence
user chooses percentage seen for review
user chooses percentage unseen for review

question suggester in my understanding would actually only be an improvement for the hardcoded portion, whereas the unseen/seen daisy-chaining is under the hood.

is that correct? if so we could probably close this for now until we test the above more thoroughly.
