### ISSUE TITLE
cosmetics

### ISSUE THREAD

**Issue by OLI9292** [Classical-SB/invisible-college-admin#115]
prompt + choice set key (see screenshot)
            key element
                text-transform: uppercase;
                color: darkgrey;
                letter-spacing:.1em;
                font-size: 0.8em;
        center read mode 
            position: absolute;
            top: 50%;
            margin-top: -100px;
        cosmetic interface updates. i'm sure this is best for demons, the question is it better for everything ... that is, do the blue buttons get  us anything in schools aside looking "scholastic?" or this 
        just a "theme"?
               new buttons:
               color: #232323;
               border-radius: 5px;
               border: 2px solid #e8e8e8;
               padding: 16px;
               font-style: italic;
               font-size: 1.5em;
               font-family: averia light;
        image cosmetic update (see screenshot)
             border: none;
             border-radius: 10px;
             
             passage filtration ... can we make the concept a slight highlight just to draw the eye? i think color: #5985c7 works pretty well.

https://playwordcraft.slack.com/archives/G8U41KZ5Z/p1549490460001500

- Image Prompt: sometimes images are stretched. on correct answer, they are restored to original proportions. should always be right dimension.

**Comment by bencbernstein** [comment]
![prompt_key_choiceset_and_button_cosmetics](https://user-images.githubusercontent.com/13627407/52597749-cc6ced80-2e21-11e9-8811-ed0789f84337.png)

**Comment by bencbernstein** [comment]
![image_cosmetic_update](https://user-images.githubusercontent.com/13627407/52597756-d0990b00-2e21-11e9-8b2d-33f0580d2a44.png)
