### ISSUE TITLE
Read Then Answer Sequences

### ISSUE THREAD

**Issue by bencbernstein** [Classical-SB/invisible-college-admin#128]
Goal: make a really good 100-200 hardcoded sequence of demons using Read then Answer. It’ll be a little tedious but it’s time well spent for learning, and a step up from what we have now. We can then do the same thing for zoology, mythology, geology, etc.

## high priority
- [x] Read Mode -> concept + image to property
- [x] Read Mode -> Concept to Property
- [x] Question -> concept + image to property questions
- [x] Bug: Can’t select passage read mode currently in sequence 
- [x] Bug: Templates Failure Error: Field "templates" argument "curriculumId" of type "ID!" is required but not provided 
- [x] cosmetics #115 

## medium priority 
- [x] Show Image above passage (associate images with passages)
- [x] Image on correct for concept

Sample Output
![screen shot 2019-02-09 at 6 55 46 pm](https://user-images.githubusercontent.com/13627407/52527801-8aff0580-2c9c-11e9-8268-360d1f7d76e6.png)

**Comment by OLI9292** [comment]
- from @bencbernstein 
Demon Specific Stories:

====(as a read, no question answer, just a Next button)
i want to be able to show:

/  (currently exists) a passage about satan
/  an image of satan, a key of satan (eg etymology) the word “satan”, and a value of satan (eg adversary in hebrew)
/  an image of satan, the word “satan”,
/  an image of satan, the caption of the image (eg Satan in the Devil’s Bible, written in the 13 century in Bohemia)
/  a key of satan (eg etymology) the word “satan”, and a value of satan (eg adversary in hebrew)

====(as question)

prompt: image of satan, a key of satan (eg etymology) the word “satan” answers: [values]
(currently exists) prompt: a key of satan (eg etymology) the word “satan” answers: [values]

===(when an answer is correct… this is also just a read mode question that comes in sequence?)

image of satan
a passage about satan (edited) 

those are my specific stories for this next iteration

**Comment by bencbernstein** [comment]
good effects
