### ISSUE TITLE
Merge Teacher Features

### ISSUE THREAD

**Issue by bencbernstein** [Classical-SB/invisible-college-admin#130]
## High Priority

- [x] Link to download password accounts in dashboard (still send welcome email with link to download user accounts... accounts are not sent as attachments (email servers reject them))
- [x] Add Students Button shows progress so user doesn't get impatient
- [x] New Front Page (Modifications = Individual, Teacher, School (school = contact us), see mockup
- [x] Port Multiplayer Gaming from enigmatic reef
- [x] Class Progress Report

## Medium Priority
- [x] Delete Student (X next to name, then alert -> are you sure you want to delete STUDENTNAME's account?)
- [x] Welcome to wordcraft modal on first sign in with link to download passwords
- [x] Forgot password 
- [x] Weekly and All Time Class Leaderboards
- [ ] Chat box (https://helpcrunch.com/ or https://www.intercom.com ?) for teacher help, only visible to logged in admin (not individual)

## Horizon 
FAQ and How to Video page and sent in welcome email
Automated Weekly Progress Report

## Mockup
![new-front](https://user-images.githubusercontent.com/13627407/52595063-fb339580-2e1a-11e9-86c5-94773bf1fd74.jpg)

**Comment by bencbernstein** [comment]
![new_teacher_dashboard](https://user-images.githubusercontent.com/13627407/52596156-a34a5e00-2e1d-11e9-915a-07dd921cbc1b.png)

**Comment by OLI9292** [comment]
what do you mean here "* Add Students Button shows progress so user doesn't get impatient" ?

**Comment by bencbernstein** [comment]
right the add students flow is breaking UX for teachers. the current hypothesis for a fix is that user needs a progress indicator when they hit FINISH in the ADD STUDENTS flow.

**Comment by bencbernstein** [comment]
awesome looking forward to QA on this
