### ISSUE TITLE
Content Resizing

### ISSUE THREAD

**Issue by bencbernstein** [Classical-SB/invisible-college-admin#131]
Cosmetics feeling really good  much cooler and more expensive than before.

Biggest quantum leap is dynamically fitting content to the screen. This is pretty high leverage as it's going to let the beauty of the images shine through and make this really feel like a gamified pictorial encyclopedia.

Border-radius: 10px applied to all images

Constraints are:
	Show the image as large as possible, while:
	Make sure the text can be shown without minimizing font size
	Make sure the buttons can be shown without minimizing font size

Now:
<img width="661" alt="now-1" src="https://user-images.githubusercontent.com/13627407/52680872-0d3f3200-2f08-11e9-94fe-29c3fe178c7d.png">
<img width="646" alt="now-2" src="https://user-images.githubusercontent.com/13627407/52680874-0f08f580-2f08-11e9-9004-c1bdd4de81c9.png">
Desired:

<img width="438" alt="desired-2a" src="https://user-images.githubusercontent.com/13627407/52680877-10d2b900-2f08-11e9-8ccf-0e24db8f9a8c.png">
<img width="790" alt="desired-2c" src="https://user-images.githubusercontent.com/13627407/52680879-10d2b900-2f08-11e9-88fe-558284528a44.png">
<img width="669" alt="desired-1" src="https://user-images.githubusercontent.com/13627407/52680880-10d2b900-2f08-11e9-96a4-219b6c09e071.png">

**Comment by OLI9292** [comment]
so the image should take up as much space as possible, after the text + button are placed at the bottom?

**Comment by bencbernstein** [comment]
correct - the text and button should be below the image and never below a minimum size.

**Comment by bencbernstein** [comment]
this is a universal principle. eg:
<img width="886" alt="screen shot 2019-02-12 at 9 09 07 pm" src="https://user-images.githubusercontent.com/13627407/52681631-82ac0200-2f0a-11e9-98e8-b4743e0e3607.png">

**Comment by OLI9292** [comment]
deployed content resize on read mode.  i'll close this for now, until we come back to image on correct
