### ISSUE TITLE
Read Mode Sequence Order Reverse

### ISSUE THREAD

**Issue by bencbernstein** [Classical-SB/invisible-college-admin#132]
I believe that read mode sequence order is reversed, while question order questions are correct.

So it seems that a sequence with a late read mode question displays that first, then asks the questions in the correct order.

**Comment by OLI9292** [comment]
lol that's a funny one.  was using (pop)[https://www.w3schools.com/jsref/jsref_pop.asp] instead of (shift)[https://www.w3schools.com/jsref/jsref_shift.asp]

**Comment by bencbernstein** [comment]
fml
