### ISSUE TITLE
Merge Issues

### ISSUE THREAD

**Issue by OLI9292** [Classical-SB/invisible-college-admin#134]
### Error
```×
TypeError: Cannot set property 'open' of undefined
Train../src/components/wordcraft/games/Train/index.tsx.Train.formatLevels
src/components/wordcraft/games/Train/index.tsx:84
  81 |     return { progress, sequence, complete, open: complete, averageAccuracy }
  82 |   })
  83 |   const unlockIdx = withProgress.findIndex(s => !s.complete)
> 84 |   withProgress[unlockIdx].open = true
  85 |   return withProgress
  86 | }
  87 | 
```

### To Reproduce
 i get this error frequently when logging in and switching curriculum to demonology. sometimes it goes away, i think, if i create another sequence:, It goes away, i think, if i create another sequence.

**Comment by OLI9292** [comment]
When I try to remove any value from a choice set, I get the following error:

<img width="650" alt="screen shot 2019-02-12 at 7 15 32 pm" src="https://user-images.githubusercontent.com/13627407/52683643-6fe8fb80-2f11-11e9-9fa4-dbc88d068fda.png">

**Comment by OLI9292** [comment]
```UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `values` of 'undefined' or 'null'. at Promise.all.doc.properties.map (/app/src/services/questionGenerators/word/wordToTag.js:9:32) ```

**Comment by bencbernstein** [comment]
Getting this error when returning to KEI after sequence testing.

![screen shot 2019-02-13 at 5 44 04 pm](https://user-images.githubusercontent.com/13627407/52749386-04596980-2fb7-11e9-96ab-13a5e1d8b9bb.png)

**Comment by bencbernstein** [comment]
I'm generally having problems viewing sequences I create. It seems to default back to zoology and give me the error listed in the comment above.

It's a tough error to reproduce, but it might be caused by having sequences with 0 questions in them?
