### ISSUE TITLE
Merge | Remaining Issues

### ISSUE THREAD

**Issue by OLI9292** [Classical-SB/invisible-college-admin#150]
## Blocking
- [x] review seen / unseen (+ confine seen to current curriculum)
- [x] non-admins should not see KEI routes
- [x] multiplayer error, @bencbernstein to post image

## Not Blocking
- [x] mobile styles
- [x] chat box + google analytics
- [x] teacher leaderboard
- [x] hinting review
- [x] root model
- [x] slack message on sign up
- [x] time played on my class
- [x] duplicate questions in sequence

## Necessary migrations before deploy

- [x] all curriculum public bool ==> access level
- [x] regenerate questions so difficulty is updated
- [x] re-type definitions for non WC words
- [x] add SENDGRID_API_KEY to heroku config
- [x] add lab and role to users

**Comment by bencbernstein** [comment]
<img width="667" alt="screen shot 2019-03-05 at 5 21 37 pm" src="https://user-images.githubusercontent.com/13627407/53842882-bd83e180-3f6e-11e9-9403-d8c2a0f391b5.png">
