### ISSUE TITLE
Usability

### ISSUE THREAD

**Issue by bencbernstein** [Classical-SB/invisible-college-admin#45]
- [ ] Highlight search term in passage filtration 
- [x] Standardize bottom nav bar in discover, library, etc
- [ ] Explanation of Red/Green on Enrich Passages
- [x] Add Description to Download Button in discover

**Comment by bencbernstein** [comment]
@OLI9292 can you outline how you'd implement highlight search term in passage filtration... just a regex? i was looking at discover's highlight but it seems the `highlight` class is from elastic search, not on the browser side?

**Comment by OLI9292** [comment]
I think we should review highlighting first and go from there.  Do we need highlighting everything (ie. read mode, filter, enrich, passage order)?  Is it always consistent?  What is the color scheme?  Should they link?  etc.

**Comment by bencbernstein** [comment]
Ok, although I would want it in sift/filter, seems like Akiva doesn't really want it and it's minor so let's punt on this for now.

**Comment by OLI9292** [comment]
ok so no highlighting for sift.  for enrich we should have a color scheme.  currently it is RED = conjunction, YELLOW = WC word, BLUE = choice set word, GREEN = focus word.  I think the color sheme needs revisions.  couple of things Akiva pointed out, (1) use duller colors so reading is easy (2) filter by curriculum, so a WC word not in the current curriculum is still highlighted (but maybe a different / even lighter) version
