### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by OLI9292** [Classical-SB/invisible-college-admin#57]

**Comment by bencbernstein** [comment]
![rob-map-1](https://user-images.githubusercontent.com/13627407/50862480-b7f08d80-1369-11e9-92f6-6578ee995ca4.jpg)
![rob-map-2](https://user-images.githubusercontent.com/13627407/50862482-b9ba5100-1369-11e9-956e-44f9e86a375f.jpg)
proposed spec. @cashmonides  @akiva should approve or modify

**Comment by akiva** [comment]
I suspect I may have been @mentioned by mistake, unless you are all looking for a hand ;) I will unsubscribe to remove myself. _Much success on your project_! Cheers.
