### ISSUE TITLE
test pdf conversion on a pdf that is just a pure image, not already converted into text

### ISSUE THREAD

**Issue by OLI9292** [Classical-SB/invisible-college-admin#60]

**Comment by OLI9292** [comment]
[Belfort,_The_Wolf_of_Wall_Street.pdf](https://github.com/Classical-SB/invisible-college-admin/files/2738232/Belfort._The_Wolf_of_Wall_Street.pdf)

**Comment by OLI9292** [comment]
https://acrobat.adobe.com/us/en/acrobat/how-to/ocr-software-convert-pdf-to-text.html

**Comment by bencbernstein** [comment]
=========

TEST RESULTS
// max image size: 250kb

accuracy of output:
seems to approach 100%

JPG Conversion
total time for pdf_to_jpgs 156.1900806427002 seconds seconds

TESSERACT OCR
total time for jpg_to_string 2059.645639896393 seconds seconds


========= 
TEST RESULTS
// max image size: 50kb

accuracy of output:
unintelligible

JPG Conversion
total time for pdf_to_jpgs 7.17741584777832 seconds

TESSERACT OCR
total time for jpg_to_string 212.1838457584381 seconds

**Comment by bencbernstein** [comment]
[belfort-250.txt](https://github.com/Classical-SB/invisible-college-admin/files/2738628/belfort-250.txt)
[belfort-50kb.txt](https://github.com/Classical-SB/invisible-college-admin/files/2738629/belfort-50kb.txt)

**Comment by bencbernstein** [comment]
code ... # split into pages and convert to JPG so pytesseract can read
import time

def pdf_to_jpgs(path, book_name):
    from pdf2image import convert_from_path

    start_time = time.time()

    # set path and max image size
    # the max image size of the image affects speed a alot
    # TODO test how much max image size affects accuracy
    pages = convert_from_path(path, 500)

    counter = 0
    for page in pages:
        #print("converting page", counter)
        counter += 1
        page.save(book_name + "/" + str(counter) + '.jpg', 'JPEG')
    end_time = time.time()
    print("total time for pdf_to_jpgs", end_time - start_time, "seconds")

pdf_to_jpgs("belfort.pdf", "belfort")

# use OCR on each JPG
def jpg_to_string(directory):
    try:
        from PIL import Image
    except ImportError:
        import Image
    import pytesseract
    import os
    from natsort import natsorted, ns

    start_time = time.time()
    text = ""
    files = natsorted(os.listdir(directory))
    print(files)
    for page in files:
        #print("scanning page", page)

        # Simple image to string
        text += pytesseract.image_to_string(Image.open(directory + page))

        # Get verbose data including boxes, confidences, line and page numbers
        #print(pytesseract.image_to_data(Image.open(directory + page)))
    end_time = time.time()
    print("total time for jpg_to_string", end_time - start_time, "seconds")
    return text

text_str = jpg_to_string(directory="belfort/")

# output as txt
text_file = open("belfort-500kb.txt", "w")
text_file.write(text_str)
text_file.close()

**Comment by bencbernstein** [comment]
```# split into pages and convert to JPG so pytesseract can read
import time

def pdf_to_jpgs(path, book_name):
    from pdf2image import convert_from_path

    start_time = time.time()

    # set path and max image size
    # the max image size of the image affects speed a alot
    # TODO test how much max image size affects accuracy
    pages = convert_from_path(path, 500)

    counter = 0
    for page in pages:
        #print("converting page", counter)
        counter += 1
        page.save(book_name + "/" + str(counter) + '.jpg', 'JPEG')
    end_time = time.time()
    print("total time for pdf_to_jpgs", end_time - start_time, "seconds")

pdf_to_jpgs("belfort.pdf", "belfort")

# use OCR on each JPG
def jpg_to_string(directory):
    try:
        from PIL import Image
    except ImportError:
        import Image
    import pytesseract
    import os
    from natsort import natsorted, ns

    start_time = time.time()
    text = ""
    files = natsorted(os.listdir(directory))
    print(files)
    for page in files:
        #print("scanning page", page)

        # Simple image to string
        text += pytesseract.image_to_string(Image.open(directory + page))

        # Get verbose data including boxes, confidences, line and page numbers
        #print(pytesseract.image_to_data(Image.open(directory + page)))
    end_time = time.time()
    print("total time for jpg_to_string", end_time - start_time, "seconds")
    return text

text_str = jpg_to_string(directory="belfort/")

# output as txt
text_file = open("belfort-500kb.txt", "w")
text_file.write(text_str)
text_file.close()```
