### ISSUE TITLE
General QA

### ISSUE THREAD

**Issue by OLI9292** [Classical-SB/invisible-college-admin#83]
- [x] /images for curriculum other than Zoology
- [x] /discover for curriculum other than Zoology
- [x] fire word question generators after create and edit
- [ ] remove "undefined" text from all questions
- [ ] POS questions should only use noun / verb / adj 
- [ ] hide non-alphabetic character indenting
- [x] Definition Erased After Uploading Image on Concept

**Comment by bencbernstein** [comment]
looks like Definition Erased After Uploading Image on Concept was fixed... other ones too?
