### ISSUE TITLE
Question "suggester" in hardcoded sequencer

### ISSUE THREAD

**Issue by OLI9292** [Classical-SB/invisible-college-admin#84]

**Comment by bencbernstein** [comment]
seems on the right track and i suspect @cashmonides will have a lot to say.

anything that suggests questions off daisy chains (aka, in a sense, minimal pairs) is going to be helpful for "hardcoded" sequences.

we also probably want a tab or sequence viewer that is just a configuration of algorithm parameters, meant to parameterize the algorithm that currently exists.

**Comment by bencbernstein** [comment]
BB  stories to solve:

As I user, I want to be able to access my data points more granularly, that is be able to generate and then see the tags (properties) and images related to the data.

I’d probably like them to default to some system of “minimal pairs” (aka daisy chain) as a starting point.

I want to create sequences quickly that are both maximally pedagogical (interrelated and cohesive) while still giving me full granular control to edit and arrange my data. (edited)

**Comment by bencbernstein** [comment]
Seeing all the possible questions for a data point is great, elucidating.

The next step may be an algo that suggests minimal pair chains (aka daisy chain) question off your seed.

We could start by trying shortest levenshtein distance of the prompt or answer with another key or value in the curriculum, picking the one with the lowest obscurity first.

Quick Example (these are kind of obscure concepts. imagine they all have pictures on them):

Seed Question: Halia lives? Answer: Island of Rhodes

Algorithm Suggests:
(daisy chain length between 2 and 6 ... algo picked 2):
Prompt: Lives in the Island of Rhodes? Answer: Hegetoria 
Prompt: Hegetoria's husband? Answer: Ochimus

Algorithm Suggests:
(back to chaining off seed)
(algo picked length 3):
Prompt:  Halia's parents?  Answer: Thalassa 
Prompt: Thalassa is god of? Answer: The sea
Prompt: Lives in the Aegean Sea? Answer: Poseidon

**Comment by bencbernstein** [comment]
closing as this has merged into issue #112
